// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/files": {
            "post": {
                "description": "Register a new file with metadata and associate it with a producer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Register a new file",
                "parameters": [
                    {
                        "description": "File registration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RegisterFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response with file ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/initDownload": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "download"
                ],
                "summary": "Init download",
                "parameters": [
                    {
                        "description": "Init download request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.InitDownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response with transfer ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/producers": {
            "post": {
                "description": "Register a new producer with UDP options for file transfer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "producers"
                ],
                "summary": "Register a new producer",
                "parameters": [
                    {
                        "description": "Producer registration options",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.RegisterProducerOptions"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response with producer ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "description": "Establishes a WebSocket connection for a producer to receive transfer notifications",
                "tags": [
                    "websocket"
                ],
                "summary": "WebSocket connection for producers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Producer ID",
                        "name": "producer_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    },
                    "400": {
                        "description": "Invalid producer ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "contract.RegisterProducerOptions": {
            "type": "object",
            "properties": {
                "udp_options": {
                    "$ref": "#/definitions/model.UdpOptions"
                }
            }
        },
        "handler.InitDownloadRequest": {
            "type": "object",
            "properties": {
                "client_udp_options": {
                    "$ref": "#/definitions/model.UdpOptions"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "handler.RegisterFileRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "producer_id": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "model.UdpOptions": {
            "type": "object",
            "properties": {
                "external_ip": {
                    "type": "string"
                },
                "external_port": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "UDPie Signaller API",
	Description:      "API for UDPie file transfer signaller service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
